const {
  DOCUMENT_TYPES,
  buildDecisionTemplate,
  buildFailedAttemptTemplate,
  buildHandoffTemplate,
  getDefaultDocsLayout,
  renderTemplate,
} = require("./templates");
const {
  classifyCommit,
  formatCommitInspection,
  getRepoRoot,
  getStagedDiff,
  getStagedFiles,
  isCodePath,
  isDecisionDocPath,
  isHighRiskPath,
  isTestPath,
  normalizeGitPath,
} = require("./checks");
const {
  applyAnswersToPlan,
  buildCommitMessage,
  cleanLine,
  cloneCommitPlan,
  normalizeCommitPlan,
  normalizeQuestions,
  normalizeSubject,
  truncateLine,
  uniqueLines,
} = require("./commit-plan");
const {
  collectContextBullets,
  generateCommitMessage,
  inferFocus,
  inferGenericWhy,
  inferScope,
  inferSubject,
  inferType,
  planCommitMessage,
  prepareCommitMessage,
  shouldAutofillMessage,
  stripComments,
} = require("./commit-message");
const {
  askQuestions,
  buildFallbackQuestions,
  getChangeCategories,
  hasAnswers,
} = require("./commit-questions");
const {
  analyzeCommitFlow,
  appendBulletsToSection,
  buildClarifyingQuestions,
  buildDraftPath,
  enrichCommitMessage,
  formatCommitFlow,
  runCommitFlow,
} = require("./commit-flow");
const {
  analyzeCommitWithLlm,
  buildPrompt,
  finalizeCommitWithLlm,
  getAvailableProviders,
  getPromptContract,
  getProviderProfile,
  resolveProvider,
} = require("./llm-analysis");
const {
  collectRepoContext,
  collectRecallContext,
  collectNearestContextPaths,
  readContextDocs,
  readDiffStat,
  readPathHistory,
  readRecentCommits,
  readSessionContext,
  readSymbolHistory,
  readRelatedReferences,
  readFocusedSymbols,
  readFocusedSnippets,
  trimContext,
} = require("./repo-context");
const {
  SESSION_EVENT_TYPES,
  beginSession,
  getSessionLayout,
  readSessionResidue,
  readSessionState,
  recordSessionEvent,
} = require("./session-state");
const {
  detectSymbolCandidate,
  findEnclosingSymbols,
  findSymbolEnd,
  isJsLikePath,
  scanJsSymbols,
  selectChangedSymbols,
} = require("./symbol-context");
const {
  buildVerificationSummary,
  runVerification,
  summarizeCommand,
  tailLines,
} = require("./verification");

const PRODUCT_NAME = "Tacit";

module.exports = {
  PRODUCT_NAME,
  DOCUMENT_TYPES,
  buildDecisionTemplate,
  buildFailedAttemptTemplate,
  buildHandoffTemplate,
  getDefaultDocsLayout,
  renderTemplate,
  classifyCommit,
  formatCommitInspection,
  getRepoRoot,
  getStagedDiff,
  getStagedFiles,
  isCodePath,
  isDecisionDocPath,
  isHighRiskPath,
  isTestPath,
  normalizeGitPath,
  applyAnswersToPlan,
  buildCommitMessage,
  cleanLine,
  cloneCommitPlan,
  collectContextBullets,
  generateCommitMessage,
  inferFocus,
  inferGenericWhy,
  inferScope,
  inferSubject,
  inferType,
  normalizeCommitPlan,
  normalizeQuestions,
  normalizeSubject,
  planCommitMessage,
  prepareCommitMessage,
  shouldAutofillMessage,
  stripComments,
  truncateLine,
  uniqueLines,
  askQuestions,
  analyzeCommitFlow,
  appendBulletsToSection,
  buildFallbackQuestions,
  buildClarifyingQuestions,
  buildDraftPath,
  enrichCommitMessage,
  formatCommitFlow,
  getChangeCategories,
  hasAnswers,
  runCommitFlow,
  analyzeCommitWithLlm,
  buildPrompt,
  finalizeCommitWithLlm,
  getAvailableProviders,
  getPromptContract,
  getProviderProfile,
  resolveProvider,
  SESSION_EVENT_TYPES,
  beginSession,
  collectRepoContext,
  collectRecallContext,
  collectNearestContextPaths,
  getSessionLayout,
  readContextDocs,
  readDiffStat,
  readPathHistory,
  readRecentCommits,
  readSessionContext,
  readSessionResidue,
  readSessionState,
  readSymbolHistory,
  readRelatedReferences,
  readFocusedSymbols,
  readFocusedSnippets,
  recordSessionEvent,
  trimContext,
  detectSymbolCandidate,
  findEnclosingSymbols,
  findSymbolEnd,
  isJsLikePath,
  buildVerificationSummary,
  runVerification,
  scanJsSymbols,
  selectChangedSymbols,
  summarizeCommand,
  tailLines,
};
